// 250 random themes for creative challenge generation
export const THEME_POOL = [
  'lemonade',
  'penguin',
  'economy',
  'midnight train',
  'ancient library',
  'robotic garden',
  'coffee shop',
  'northern lights',
  'forgotten letter',
  'street musician',
  'underwater city',
  'butterfly migration',
  'clockwork bird',
  'abandoned carnival',
  'thunderstorm',
  'recipe book',
  'desert oasis',
  'paper airplane',
  'glass blower',
  'lighthouse keeper',
  'chess tournament',
  'honeycomb',
  'satellite dish',
  'vintage camera',
  'monsoon rain',
  'bookstore cat',
  "astronaut's dream",
  'cobblestone alley',
  'wind chimes',
  'origami crane',
  'midnight bakery',
  'crystal cave',
  'ferry crossing',
  'street painter',
  'snow globe',
  'typewriter',
  'lunar eclipse',
  'fish market',
  'old radio',
  'campfire stories',
  'hot air balloon',
  'rain puddle',
  'antique shop',
  'mountain echo',
  'candle maker',
  'subway platform',
  'telescope',
  'bamboo forest',
  'flea market',
  'stargazing',
  'tide pools',
  'carousel',
  'thrift store',
  'constellation',
  'blacksmith',
  'greenhouse',
  'train station',
  'mosaic tiles',
  'ocean liner',
  'vineyard',
  'cathedral bells',
  'night market',
  'pottery wheel',
  'aurora',
  'sailing ship',
  'chocolate factory',
  'mountain trail',
  'jazz club',
  'flower shop',
  'observatory',
  'ice sculpture',
  'fishing village',
  'antique clock',
  'coral reef',
  'rooftop garden',
  'spice bazaar',
  'frozen lake',
  'violin maker',
  'canyon echo',
  'lantern festival',
  'bird sanctuary',
  'bookbinder',
  'thundercloud',
  'silk road',
  'lighthouse',
  'mushroom forest',
  'harbor dawn',
  'quilt maker',
  'solar eclipse',
  'tea ceremony',
  'abandoned factory',
  'firefly field',
  'windmill',
  'meteor shower',
  'maple syrup',
  'underground river',
  'kite festival',
  'copper smith',
  'dolphin pod',
  'autumn market',
  'stained glass',
  'wolf pack',
  'cave painting',
  'sunset cruise',
  'herbalist',
  'dragon nest',
  'pirate treasure',
  'wizard tower',
  'fairy ring',
  'troll bridge',
  'enchanted mirror',
  'magic carpet',
  'crystal ball',
  'spell book',
  'potion shop',
  'time machine',
  'parallel universe',
  'quantum garden',
  'cyberpunk city',
  'steampunk airship',
  'alien embassy',
  'robot uprising',
  'post-apocalyptic market',
  'floating islands',
  'crystal palace',
  'dragon rider',
  'mermaid song',
  'phoenix ashes',
  'unicorn horn',
  'centaur forest',
  'haunted mansion',
  'ghost ship',
  'vampire castle',
  'werewolf moon',
  'zombie apocalypse',
  'medieval feast',
  'samurai duel',
  'viking longship',
  'egyptian tomb',
  'mayan temple',
  'roman coliseum',
  'greek oracle',
  'norse mythology',
  'celtic knot',
  'chinese dragon',
  'japanese garden',
  'african savanna',
  'arctic expedition',
  'amazon rainforest',
  'deep sea trench',
  'volcanic island',
  'crater lake',
  'geyser valley',
  'salt flat',
  'sand dunes',
  'cherry blossom',
  'falling leaves',
  'winter solstice',
  'spring awakening',
  'summer storm',
  'broken compass',
  'lost map',
  'treasure hunt',
  'secret passage',
  'hidden door',
  'whispering wind',
  'singing stone',
  'dancing shadow',
  'silent moon',
  'burning star',
  'iron gate',
  'golden key',
  'silver thread',
  'bronze bell',
  'crown jewel',
  'royal decree',
  'secret treaty',
  'forgotten war',
  'peace summit',
  'revolution spark',
  'spy network',
  'underground railroad',
  'freedom fighter',
  'resistance leader',
  'peaceful protest',
  'wedding day',
  'birth announcement',
  'reunion dinner',
  'farewell party',
  'graduation ceremony',
  'first day of school',
  'last day of summer',
  'new year eve',
  'birthday surprise',
  'anniversary gift',
  'detective noir',
  'courtroom drama',
  'heist plan',
  'escape room',
  'murder mystery',
  'love letter',
  'breakup note',
  'apology card',
  'congratulations text',
  'job offer email',
  'space station',
  'moon colony',
  'mars mission',
  'asteroid mining',
  'black hole',
  'parallel world',
  'dream world',
  'virtual reality',
  'augmented reality',
  'holographic concert',
  'ancient scroll',
  'clay tablet',
  'stone inscription',
  'cave art',
  'hieroglyphics',
  'orchestra pit',
  'opera house',
  'ballet stage',
  'circus tent',
  'theater premiere',
  'art gallery',
  'sculpture garden',
  'film festival',
  'music festival',
  'poetry reading',
  'cooking competition',
  'baking disaster',
  'recipe swap',
  'food truck',
  'street food market',
  'farmers market',
  'flower garden',
  'herb garden',
  'vegetable patch',
  'fruit orchard',
  'dog park',
  'cat cafe',
  'bird watching',
  'butterfly house',
  'aquarium',
  'zoo escape',
  'safari adventure',
  'whale watching',
  'dolphin rescue',
  'turtle hatching',
  'tree house',
  'fortress wall',
  'castle dungeon',
  'tower balcony',
  'secret garden',
  'rainy afternoon',
  'snowy morning',
  'windy evening',
  'foggy night',
  'starry midnight',
  'birthday cake',
  'wedding dress',
  'graduation cap',
  'holiday lights',
  'new year fireworks',
  'old photograph',
  'faded painting',
  'worn-out shoes',
  'torn photograph',
  'rusty bicycle',
  'abandoned playground',
  'empty swimming pool',
  'forgotten train tracks',
  'dusty bookshelf',
  'cobwebbed attic',
  'moonlit beach',
  'sunset cliffs',
  'dawn meadow',
  'noon desert',
  'twilight forest',
  'rainbow bridge',
  'thunderbolt strike',
  'lightning storm',
  'hail damage',
  'tornado watch',
  'ice cream truck',
  'cotton candy',
  'ferris wheel',
  'roller coaster',
  'carousel horses',
  'magic show',
  'escape artist',
  'juggling act',
  'tightrope walker',
  'clown car',
  'puppet theater',
  'shadow puppets',
  'marionette show',
  'ventriloquist dummy',
  'mime artist',
  'jazz band',
  'rock concert',
  'symphony hall',
  'street performer',
  'busker corner',
  'book club',
  'writing workshop',
  'painting class',
  'dance lesson',
  'cooking class',
  'yoga retreat',
  'meditation center',
  'spa day',
  'massage therapy',
  'aromatherapy session',
  'camping trip',
  'hiking trail',
  'rock climbing',
  'river rafting',
  'kayaking adventure',
  'scuba diving',
  'snorkeling reef',
  'surfing waves',
  'sailing regatta',
  'fishing trip',
  'ski resort',
  'snowboarding park',
  'ice skating rink',
  'sledding hill',
  'snowball fight',
  'picnic blanket',
  'barbecue grill',
  'bonfire night',
  'stargazing trip',
  'nature walk',
  'botanical garden',
  'rose garden',
  'zen garden',
  'english garden',
  'japanese tea garden',
  'castle ruin',
  'ancient temple',
  'pyramid tomb',
  'colosseum',
  'great wall',
  'taj mahal',
  'machu picchu',
  'petra city',
  'angkor wat',
  'christ the redeemer',
  'space telescope',
  'particle accelerator',
  'quantum computer',
  'dna sequencer',
  'robot surgeon',
  '3d printer',
  'drone delivery',
  'self-driving car',
  'smart home',
  'virtual assistant',
  'augmented reality',
  'artificial intelligence',
  'machine learning',
  'deep learning',
  'neural network',
  'blockchain',
  'cryptocurrency',
  'nft art',
  'metaverse world',
  'digital twin',
  'cyber attack',
  'data breach',
  'phishing email',
  'ransomware note',
  'firewall breach',
  'startup pitch',
  'venture capital',
  'angel investor',
  'ipo launch',
  'unicorn company',
  'food delivery',
  'ride sharing',
  'home sharing',
  'co-working space',
  'pop-up shop',
  'farm to table',
  'slow food movement',
  'zero waste',
  'circular economy',
  'green energy',
  'climate change',
  'ocean acidification',
  'deforestation',
  'species extinction',
  'plastic pollution',
  'renewable energy',
  'solar panels',
  'wind turbine',
  'geothermal plant',
  'tidal generator',
  'electric vehicle',
  'hydrogen fuel',
  'biofuel crop',
  'carbon capture',
  'green building',
  'vertical farm',
  'lab-grown meat',
  'plant-based diet',
  'precision agriculture',
  'smart irrigation',
  'space tourism',
  'lunar base',
  'mars colony',
  'asteroid mining',
  'orbital hotel',
  'deep space probe',
  'interstellar mission',
  'alien contact',
  'first contact protocol',
  'galactic federation',
  'time travel paradox',
  'butterfly effect',
  'grandfather paradox',
  'bootstrap paradox',
  'multiverse theory',
  'quantum entanglement',
  'dark matter',
  'dark energy',
  'black hole merger',
  'gravitational wave',
  'neutron star',
  'supernova explosion',
  'gamma ray burst',
  'cosmic microwave background',
  'big bang theory',
  'string theory',
  'm-theory',
  'loop quantum gravity',
  'holographic principle',
  'anthropic principle',
  'faster than light',
  'warp drive',
  'wormhole travel',
  'hyperspace jump',
  'subspace communication',
  'teleportation',
  'matter replicator',
  'holodeck',
  'force field',
  'invisibility cloak',
  'mind reading',
  'telekinesis',
  'precognition',
  'telepathy',
  'psychic powers',
  'magic system',
  'mana pool',
  'spell casting',
  'enchantment',
  'curse breaking',
  'sword fighting',
  'archery range',
  'shield wall',
  'cavalry charge',
  'siege warfare',
  'naval battle',
  'aerial combat',
  'space battle',
  'mecha fight',
  'kaiju attack',
  'monster hunting',
  'dungeon crawling',
  'treasure vault',
  'puzzle room',
  'trap corridor',
  'boss encounter',
  'final showdown',
  'epic quest',
  'side quest',
  'random encounter',
  'level up',
  'skill tree',
  'character creation',
  'party assembly',
  'guild hall',
  'tavern brawl',
  'inn rest',
  'market shopping',
  'blacksmith forge',
  'alchemist shop',
  'healing potion',
  'mana potion',
  'scroll of wisdom',
  'ring of power',
  'cloak of shadows',
  'enchanted weapon',
  'legendary armor',
  'cursed item',
  'ancient artifact',
  'world-ending weapon',
  'chosen one',
  'prophecy',
  'destiny call',
  'hero journey',
  'villain origin',
  'redemption arc',
  'betrayal',
  'sacrifice',
  'alliance',
  'rivalry',
  'mentor figure',
  'sidekick',
  'comic relief',
  'wise elder',
  'trickster god',
  'dragon hoard',
  'unicorn tears',
  'phoenix rebirth',
  'griffin flight',
  'centaur wisdom',
  'mermaid song',
  'siren call',
  'kraken rising',
  'leviathan deep',
  'hydra heads',
  'chimera form',
  'basilisk gaze',
  'cockatrice stone',
  'manticore sting',
  'werewolf transformation',
  'vampire bite',
  'zombie horde',
  'ghost whisper',
  'poltergeist activity',
  'demon summoning',
  'angel wings',
  'divine intervention',
  'holy light',
  'unholy darkness',
  'balance restored',
  'good vs evil',
  'order vs chaos',
  'freedom vs control',
  'truth vs lies',
  'love vs duty',
  'honor vs survival',
  'justice vs mercy',
  'knowledge vs ignorance',
  'hope vs despair',
  'life vs death'
];

/**
 * Fisher-Yates shuffle for uniform random selection
 */
function fisherYatesShuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Pick N unique random themes from the pool (2-4 by default)
 */
export function pickRandomThemes(count) {
  const n = typeof count === 'number' ? count : Math.floor(Math.random() * 3) + 2; // 2 to 4

  const shuffled = fisherYatesShuffle(THEME_POOL);
  return shuffled.slice(0, Math.min(n, THEME_POOL.length));
}
